title: <p align="center"> María Aguilera García  </p>

logo: "/images/picture4.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume2.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/maria-aguilera-garcia/">LinkedIn</a> |
  <a href=""https://github.com/maria-aguilera">GitHub</a>
  </p>
  
  <p align="justify">
  Econometrics, big data, machine learning, coding and data science passionate.
  <br><br>
  MS degree in Business Analytics and Big Data (specialization in Applied Artificial Intelligence) at IE School of Human Sciences and Technology.
  <br><br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

