title: <p align="center"> Maria Aguilera </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/maria-aguilera-garcia/">LinkedIn</a> |
  <a href="https://github.com/maria-aguilera"">GitHub</a>
  </p>
  
  <p align="justify">
  Econometrics, big data, machine learning, coding and data science passionate.
  <br><br>
  MS degree in Business Analytics and Big Data (specialization in Applied Artificial Intelligence) at IE School of Human Sciences and Technology.  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID
